OnlineShop/Controllers/ShoppingCartController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using OnlineShop.Core.Interfaces;
using OnlineShop.Models.ViewModels;

namespace OnlineShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IDatabaseHelper _databaseHelper;
        private readonly string _cartId;

        public ShoppingCartController(IDatabaseHelper databaseHelper, IClientStorageService clientStorageService)
        {
            _databaseHelper = databaseHelper;
            _cartId = clientStorageService.GetCartId();
        }

        public async Task<ActionResult> Index()
        {
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = await _databaseHelper.GetCartItemsAsync(_cartId),
                CartTotal = await _databaseHelper.GetTotalAsync(_cartId)
            };

            return View(viewModel);
        }

        public async Task<ActionResult> AddToCart(int id)
        {
            var addedAlbum = await _databaseHelper.GetAlbumAsync(id);
            var cart = _databaseHelper.AddToCartAsync(addedAlbum, _cartId);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> RemoveFromCart(int id)
        {
            var albumName = await _databaseHelper.GetAlbumNameAsync(id);
            var itemCount = await _databaseHelper.RemoveFromCartAsync(id, _cartId);
            var results = new ShoppingCartRemoveViewModel()
            {
                Message = Server.HtmlEncode(albumName) + " has been removed from your shopping cart.",
                CartTotal = await _databaseHelper.GetTotalAsync(_cartId),
                CartCount = await _databaseHelper.GetCountAsync(_cartId),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            ViewBag.CartCount = _databaseHelper.GetCount(_cartId);
            return PartialView("CartSummary");
        }
    }
}

OnlineShop/Controllers/StoreController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using OnlineShop.Core.Interfaces;

namespace OnlineShop.Controllers
{
    public class StoreController : Controller
    {
        private readonly IDatabaseHelper _databaseHelper = null;

        public StoreController(IDatabaseHelper databaseHelper)
        {
            _databaseHelper = databaseHelper;
        }

        public async Task<ActionResult> Index()
        {
            return View(await _databaseHelper.GetGenresAsync());
        }

        public ActionResult Browse(string genre)
        {
            var model = _databaseHelper.GetGenreWithAlbums(genre);
            return View(model);
        }

        public async Task<ActionResult> Details(int id)
        {
            return View(await _databaseHelper.GetAlbumAsync(id));
        }

        public ActionResult GenreMenu()
        {
            var genres = _databaseHelper.GetGenres(); 
            return PartialView(genres);
        }
    }
}

OnlineShop/Views/Store/Browse.cshtml
@model OnlineShop.Core.Database.Genre

@{
    ViewBag.Title = "Browse Albums";
}

<div class="genre">
    <h3><em>@Model.Name</em> Albums</h3>

    <ul id="album-list">
        @foreach (var album in Model.Albums)
        {
            <li>
                <a href="@Url.Action("Details",
                    new { id = album.Id })">
                    <img alt="@album.Title"
                         src="@album.AlbumArtUrl" />
                    <span>@album.Title</span>
                </a>
            </li>
        }
    </ul>
</div>

OnlineShop/Views/Store/Details.cshtml
@model OnlineShop.Core.Database.Album

@{
    ViewBag.Title = "Details";
}

<h2>@Model.Title</h2>
<p>
    <img alt="@Model.Title"
         src="@Model.AlbumArtUrl" />
</p>
<div id="album-details">
    <p>
        <em>Genre:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>Artist:</em>
        @Model.Artist.Name
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}", Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = Model.Id }, "")
    </p>
</div>

OnlineShop/Views/Store/GenreMenu.cshtml
@model IEnumerable<OnlineShop.Core.Database.Genre>

<ul id="categories">
    @foreach (var genre in Model)
    {
        <li>
            @Html.ActionLink(genre.Name, "Browse", "Store", new { Genre = genre.Name }, null)
        </li>
    }
</ul>

OnlineShop/Views/Store/Index.cshtml
@model IEnumerable<OnlineShop.Core.Database.Genre>

@{
    ViewBag.Title = "Store";
}

<h3>Browse Genres</h3>
<p>
    Select from @Model.Count()
    genres:
</p>
<ul>
    @foreach (var genre in Model)
    {
        <li>@Html.ActionLink(genre.Name, "Browse", new { genre = genre.Name })</li>
    }
</ul>